version: '3.4'

services:
  customers-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1234

  crmit-customers:
    image: dropik/crmit-customers:staging
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+
      - CONNECTIONSTRINGS__CUSTOMERSDB=Server=customers-db; Database=CustomersDB; User ID=sa; Password=Password1234;
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/crmit.customers.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
    volumes:
      - ${HOME}/.aspnet/https:/https/
    depends_on:
      - customers-db
    ports:
      - 8001:443
