version: '3.4'

services:
  customers-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=CustomersDB
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=customers_service
      - MYSQL_PASSWORD=password

  crmit-customers:
    image: dropik/crmit-customers:staging
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+
      - DB__SERVER=customers-db
      - DB__PORT=3306
      - DB__DATABASE=CustomersDB
      - DB__USER=customers_service
      - DB__PASSWORD=password
    depends_on:
      - customers-db
    ports:
      - 8000:80
