version: '3.4'

services:
  customers-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=CustomersDB
    networks:
      - crmit-customers

  crmit-customers:
    image: dropik/crmit-customers:v1.0.0-preview
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - customers-db
    links:
      - 'customers-db:db'
    networks:
      - crmit-services
      - crmit-customers

networks:
  crmit-services:
    name: crmit-services

  crmit-customers:
    name: crmit-customers