version: '3.4'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=CustomersDB
    ports:
      - 3306:3306

  crmit-customers:
    image: dropik/crmit-customers:v1.0.0-preview
    depends_on:
      - db
    ports:
      - 8080:80
